/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'awsNetworkPeering', { get: function () { return require('./aws-network-peering'); } });
Object.defineProperty(exports, 'awsTransitGatewayAttachment', { get: function () { return require('./aws-transit-gateway-attachment'); } });
Object.defineProperty(exports, 'azurePeeringConnection', { get: function () { return require('./azure-peering-connection'); } });
Object.defineProperty(exports, 'boundaryCluster', { get: function () { return require('./boundary-cluster'); } });
Object.defineProperty(exports, 'consulCluster', { get: function () { return require('./consul-cluster'); } });
Object.defineProperty(exports, 'consulClusterRootToken', { get: function () { return require('./consul-cluster-root-token'); } });
Object.defineProperty(exports, 'consulSnapshot', { get: function () { return require('./consul-snapshot'); } });
Object.defineProperty(exports, 'hvn', { get: function () { return require('./hvn'); } });
Object.defineProperty(exports, 'hvnPeeringConnection', { get: function () { return require('./hvn-peering-connection'); } });
Object.defineProperty(exports, 'hvnRoute', { get: function () { return require('./hvn-route'); } });
Object.defineProperty(exports, 'iamWorkloadIdentityProvider', { get: function () { return require('./iam-workload-identity-provider'); } });
Object.defineProperty(exports, 'packerChannel', { get: function () { return require('./packer-channel'); } });
Object.defineProperty(exports, 'packerChannelAssignment', { get: function () { return require('./packer-channel-assignment'); } });
Object.defineProperty(exports, 'packerRunTask', { get: function () { return require('./packer-run-task'); } });
Object.defineProperty(exports, 'project', { get: function () { return require('./project'); } });
Object.defineProperty(exports, 'servicePrincipal', { get: function () { return require('./service-principal'); } });
Object.defineProperty(exports, 'servicePrincipalKey', { get: function () { return require('./service-principal-key'); } });
Object.defineProperty(exports, 'vaultCluster', { get: function () { return require('./vault-cluster'); } });
Object.defineProperty(exports, 'vaultClusterAdminToken', { get: function () { return require('./vault-cluster-admin-token'); } });
Object.defineProperty(exports, 'vaultPlugin', { get: function () { return require('./vault-plugin'); } });
Object.defineProperty(exports, 'vaultSecretsApp', { get: function () { return require('./vault-secrets-app'); } });
Object.defineProperty(exports, 'vaultSecretsSecret', { get: function () { return require('./vault-secrets-secret'); } });
Object.defineProperty(exports, 'dataHcpAwsNetworkPeering', { get: function () { return require('./data-hcp-aws-network-peering'); } });
Object.defineProperty(exports, 'dataHcpAwsTransitGatewayAttachment', { get: function () { return require('./data-hcp-aws-transit-gateway-attachment'); } });
Object.defineProperty(exports, 'dataHcpAzurePeeringConnection', { get: function () { return require('./data-hcp-azure-peering-connection'); } });
Object.defineProperty(exports, 'dataHcpBoundaryCluster', { get: function () { return require('./data-hcp-boundary-cluster'); } });
Object.defineProperty(exports, 'dataHcpConsulAgentHelmConfig', { get: function () { return require('./data-hcp-consul-agent-helm-config'); } });
Object.defineProperty(exports, 'dataHcpConsulAgentKubernetesSecret', { get: function () { return require('./data-hcp-consul-agent-kubernetes-secret'); } });
Object.defineProperty(exports, 'dataHcpConsulCluster', { get: function () { return require('./data-hcp-consul-cluster'); } });
Object.defineProperty(exports, 'dataHcpConsulVersions', { get: function () { return require('./data-hcp-consul-versions'); } });
Object.defineProperty(exports, 'dataHcpHvn', { get: function () { return require('./data-hcp-hvn'); } });
Object.defineProperty(exports, 'dataHcpHvnPeeringConnection', { get: function () { return require('./data-hcp-hvn-peering-connection'); } });
Object.defineProperty(exports, 'dataHcpHvnRoute', { get: function () { return require('./data-hcp-hvn-route'); } });
Object.defineProperty(exports, 'dataHcpOrganization', { get: function () { return require('./data-hcp-organization'); } });
Object.defineProperty(exports, 'dataHcpPackerBucketNames', { get: function () { return require('./data-hcp-packer-bucket-names'); } });
Object.defineProperty(exports, 'dataHcpPackerImage', { get: function () { return require('./data-hcp-packer-image'); } });
Object.defineProperty(exports, 'dataHcpPackerIteration', { get: function () { return require('./data-hcp-packer-iteration'); } });
Object.defineProperty(exports, 'dataHcpPackerRunTask', { get: function () { return require('./data-hcp-packer-run-task'); } });
Object.defineProperty(exports, 'dataHcpProject', { get: function () { return require('./data-hcp-project'); } });
Object.defineProperty(exports, 'dataHcpServicePrincipal', { get: function () { return require('./data-hcp-service-principal'); } });
Object.defineProperty(exports, 'dataHcpVaultCluster', { get: function () { return require('./data-hcp-vault-cluster'); } });
Object.defineProperty(exports, 'dataHcpVaultPlugin', { get: function () { return require('./data-hcp-vault-plugin'); } });
Object.defineProperty(exports, 'dataHcpVaultSecretsApp', { get: function () { return require('./data-hcp-vault-secrets-app'); } });
Object.defineProperty(exports, 'dataHcpVaultSecretsSecret', { get: function () { return require('./data-hcp-vault-secrets-secret'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

